# Generated by Django 4.1.3 on 2022-12-08 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='select_books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='articles.book'),
        ),
    ]
