# Generated by Django 4.1.3 on 2022-12-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('users', '0002_user_select_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='select_books',
        ),
        migrations.AddField(
            model_name='user',
            name='select_books',
            field=models.ManyToManyField(null=True, related_name='book_user', to='articles.book'),
        ),
    ]
