# Generated by Django 4.1.3 on 2022-12-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('users', '0003_remove_user_select_books_user_select_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='select_books',
            field=models.ManyToManyField(related_name='book_user', to='articles.book'),
        ),
    ]
