# Generated by Django 4.1.3 on 2022-12-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_select_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_auth',
            field=models.BooleanField(default=False),
        ),
    ]
