# Generated by Django 4.1.3 on 2022-12-09 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_email_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_email_auth',
            new_name='verified',
        ),
    ]
